// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('app', ['selectAddress']);

  app.controller('appCtrl', function($scope) {
    //$scope.address = "广东";
    //$scope.p = '广东';
    //$scope.c = '梅州';
    //$scope.a = '平远县';
    //$scope.d = '大柘镇';
  });

  angular.bootstrap(document, ['app']);

}).call(this);

//# sourceMappingURL=index.map
